# Generated by Django 4.0.1 on 2022-01-17 09:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0008_rename_user_user1'),
    ]

    operations = [
        migrations.AddField(
            model_name='customuser',
            name='test_res',
            field=models.BooleanField(default=False),
        ),
    ]
